### ISSUE TITLE
Node logo in case of missing images

### ISSUE THREAD

**Issue by RussellSenior** [personaltelco/ptp-openwrt-files#9]
When the node has no logo, the PTP_LOGO_PTP sed infrastructure is not invoked, leaving PTP_LOGO_PTP in the splash.html file deployed.  In this case, perhaps we should substitute the generic PTP logo?

**Comment by keeganquinn** [comment]
I think this issue can be closed. Line 105 in `FOOCAB.pl` does this.

**Comment by RussellSenior** [comment]
Indeed. Fixed in: https://github.com/personaltelco/ptp-openwrt-files/commit/8aec30f0d8ef58a30bb74526f5abbc39d8ef34bf
